config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'films' => 'films#index', as: 'films'
  root 'application#home'
  get 'films/new' => 'films#new', as: 'film_new'
  get 'films/:id' => 'films#show', as: 'film'
  get 'films/:id/edit' => 'films#edit', as: 'film_edit'
  post 'films' => 'films#create', as: 'film_create'
  patch 'films/:id' => 'films#update', as: 'film_update'
  delete 'films/:id' => 'films#delete', as: 'film_delete'

  get 'movie_search' => 'movie_searches#index', as:'movie_search'

end

app/models/ability.rb
class Ability
 include CanCan::Ability

 def initialize(user)
   user ||= User.new # guest user (not logged in)
   # can :read, Post

   can [:create, :update, :destroy, :read], Film do |film|
     film.user == user
   end
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/film.rb
class Film < ApplicationRecord
  belongs_to :user
end

app/models/movie_search.rb
class MovieSearch < ApplicationRecord
  include HTTParty
  base_uri "http://www.omdbapi.com/?apikey=36120b99&s="

  def self.search search_term
    response = get("#{search_term}")
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :films, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include CanCan::ControllerAdditions

  rescue_from CanCan::AccessDenied do |exception|
    flash[:notice] = "Access denied!"
    flash.keep(:notice)
    redirect_to root_url
  end

  def home
    render 'users/home'
  end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
before_action :authenticate_user!
load_and_authorize_resource  only: [:edit, :update, :destroy, :read]

  def index
    @user = current_user
    @films = @user.films.paginate(page: params[:page], per_page: 3)
  end

  def show
    @user = current_user
    @film = @user.films.find(params[:id])
  end

  def new
    @film = Film.new
  end

  def edit
    @film = Film.find(params[:id])
  end

  def create
    puts "create a favorite film here"
    @user = current_user
    @film = @user.films.create(user_id: @user.id, title: params["film"]["title"], year: params["film"]["year"], genre: params["film"]["genre"], synopsis: params["film"]["synopsis"], picture: params["film"]["picture"])

    respond_to do |format|
      if @film.save
        format.html { redirect_to film_path(@film), notice: 'Film was successfully created.' }
        format.json { render :show, status: :created, location: @film }
      else
        format.html { render :new }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @user = current_user
    @film = @user.films.find(params[:id])
    @film.update(title: params["film"]["title"], year: params["film"]["year"], genre: params["film"]["genre"], synopsis: params["film"]["synopsis"], picture: params["film"]["picture"])
    redirect_to film_path(@film)
  end

  def delete
    @film = Film.find(params[:id])
    @film.delete
    redirect_to films_path
  end

end

app/controllers/movie_searches_controller.rb
class MovieSearchesController < ApplicationController

  def index
    if params["/movie_search"]
      search_term = search_params.to_h[:search_term]
      @movies = MovieSearch.search(search_term)
      @movies_array = @movies["Search"]
      if @movies_array == nil
        @no_results_message = "Your search yielded no results"
      else
        @movie_results = @movies_array.paginate(page: params[:page], per_page: 5)
      end
    end
  end

  private
  def search_params
    params.require("/movie_search")
      .permit(:search_term)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/movie_searches_helper.rb
module MovieSearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/films/_form.html.erb
<%= form_for @film do |f| %>
  <%= f.label :title %>:
  <%= f.text_field :title %><br>

  <%= f.label :year %>
  <%= f.text_field :year %><br>

  <%= f.label :genre %>
  <%= f.text_field :genre %><br>

  <%= f.label :synopsis %>
  <%= f.text_field :synopsis %><br>

  <%= f.label :picture, 'Image URL' %>
  <%= f.text_field :picture %><br>

  <%= f.submit %>
<% end %>

app/views/films/edit.html.erb
<h2><%= "Edit #{@film.title}" %></h2>
<%= render 'form' %>

<br>
<%= link_to "Nevermind", film_path %>
<br><br>
<%= button_to "Delete #{@film.title}", film_delete_path(@film), method: 'delete', class: 'btn btn-danger', data: {confirm: "Are you sure you want to delete #{@film.title}?"} %>

app/views/films/index.html.erb
<h2 class='text-center'>Your Favorite Films <span><%= link_to '+', film_new_path %></span></h2>


<main class='movies_container'>
  <% @films.each do |film|%>
    <div class='each_movie'>
      <%= image_tag("#{film.picture}", height: '300') %>
      <p><strong><%= link_to film.title, film_path(film) %></strong>
      <%= " (#{film.year}) - "%>
      <i><small><%= film.genre %></small></i></p>
    </div>
  <% end %>
</main>
<div class="text-center"><%= will_paginate @films %></div>

app/views/films/new.html.erb
<h2>Add a New Film</h2>
<%= render 'form' %>
<br>
<%= link_to "Nevermind", films_path %>

app/views/films/show.html.erb
<h2><%= "#{@film.title} (#{@film.year}) - "%><small><i><%= @film.genre %></i></small></h2>

<%= image_tag (@film.picture), height: '500' %>
<p>Synopsis: <%= @film.synopsis %> </p>

<%= link_to "Edit #{@film.title}", film_edit_path(@film) %>
<br>

<%= link_to "See All Favorite Films", films_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Questrial' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if user_signed_in? %>
      <nav class='user_nav_bar'>
      <p>Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to "Logout", destroy_user_session_path, method: :delete %></p>
      <%= link_to "Edit My Account", edit_user_registration_path %>
      </nav>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path %> |
      <%= link_to "Login", new_user_session_path  %>
    <% end %>
    <h1 class='page_header text-center'><%= link_to "MovieApp", root_path %></h1>
    <%= yield %>
  </body>
</html>

app/views/movie_searches/index.html.erb
<h2>Movie Search</h2>

<%= form_for movie_search_path, method: :get do |f|%>
  <%= f.label :search_term, "Search for a movie title" %>
  <%= f.text_field :search_term %>

  <%= f.submit "Search"%>
<% end %>


<% if @movie_results %>
  <p>Your search found the following results: </p>
  <ul>
    <% @movie_results.each do |movie| %>
      <li><%= movie["Title"] %>
        <% if user_signed_in? %> |
        <%= link_to "Add to Favorites",film_create_path() %>
        <% end %>
      </li>
    <% end %>
  </ul>
<%= will_paginate @movie_results %>
<% end %>



<% if @no_results_message %>
  <p><%= @no_results_message %></p>
<% end %>

app/views/users/home.html.erb
<div class='theater_image_container'>
  <%= image_tag('http://content.mycutegraphics.com/graphics/movie/kids-watching-movie-in-theater.png', alt:'kids-watching-movie-in-theater', class:'theater_image') %>
</div>

<nav class='home_nav'>
  <% if user_signed_in? %>
    <%= link_to "See your favorite films", films_path, class: 'home_nav_link' %>
    <span class='separator_pipe'>|</span>
    <%= link_to "Add a new film to your favorites", film_new_path, class: 'home_nav_link' %>
    <span class='separator_pipe'>|</span>
    <%= link_to "Search for a film", movie_search_path, class: 'home_nav_link' %>
  <% else %>
    <p class='text-center'><%= link_to "Search For a Film", movie_search_path, class: 'home_nav_link' %></p>
  <% end %>
</nav>